# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.2
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
#  - external scripts ...

#[cartographer]
#klipper_section: mcu scanner
#is_klipper_fw: false
#action_command: git -C ~/cartographer_firmware pull
#action_command: ~/cartographer_firmware/fw_update.sh

[rpi]
klipper_section: mcu rpi
action_command: make flash

#[beacon]
#is_klipper_fw: false
#quiet_command: sudo systemctl stop klipper
#action_command: git -C ~/beacon_klipper pull
#action_command: ~/beacon_klipper/update_firmware.py update all

[leviathan]
klipper_section: mcu
# catalyst on usb-serial port (using bootloader_usb.py)
action_command: ~/klippy-env/bin/python3 ~/ukam/bootloader_usb.py /dev/serial/by-id/usb-Klipper_stm32f446xx_26005C000A51313133353932-if00
quiet_command: sleep 1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_26005C000A51313133353932-if00

[nhk36]
klipper_section: mcu
# catalyst on usb-serial port (using bootloader_usb.py)
action_command: ~/klippy-env/bin/python3 ~/ukam/bootloader_usb.py /dev/serial/by-id/usb-Klipper_rp2040_4E363334320D8124-if00
quiet_command: sleep 1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_rp2040_4E363334320D8124-if00
